pieceofsh/__init__.py
from functools import partial
from os import getenv

from quart import Quart

__version__ = '0.1.0'


def create_app(config: dict):
    app = Quart(__name__,
                template_folder='./templates',
                static_folder='./static',
                static_url_path='/static')

    from . import views
    app.register_blueprint(views.bp)
    app.config.update(config)

    return app


prod_app = partial(create_app, config={'REDIS_ADDR': getenv('REDIS_ADDR')})
dev_app = partial(create_app, config={'REDIS_ADDR': 'redis://localhost'})

pieceofsh/views.py
# std lib
import re
import uuid

# deps
from loguru import logger
from quart import (
    Blueprint,
    request,
    render_template,
    redirect,
    url_for
)
import validators

# app imports
from pieceofsh import reasons

# flask blueprint
bp = Blueprint('views', __name__)


@bp.route('/')
async def index():
    """ Returns the topic-associated page if a subdomain is used
    otherwise show the generic default page.
    """
    if not subdomain_used(request.host):
        # if no subdomains used, return default page
        logger.info(f"Host: {request.host} - Returning default page.")
        return await render_template('default.j2.html')

    topic = get_topic(request.host)
    rs = [r async for r in reasons.get_reasons(topic)]
    return await render_template('topic.j2.html',
                                 topic=topic.upper(),
                                 reasons=rs)


@bp.route('/redirect', methods=('GET', 'POST'))
async def form_redirect():
    """ The endpoint used by the text field on the default page.
    Just redirects you to whatever topic you put in.
    """
    if request.method == 'GET':
        return redirect(url_for('views.index'))

    form = await request.form
    topic = form.get('topic')

    if topic is None or topic == '':
        return "You must provide a 'topic' to be redirected to.", 400

    return redirect(f'https://{topic}.pieceof.sh/')


@bp.route('/new_reason', methods=('POST',))
async def new_reason():
    form = await request.form
    text = form.get('text')
    if not text:
        return "You must provide a 'text'.", 400
    link = form.get('link', '')
    if link != '' and not validators.url(link):
        return f"{link!r} is not a valid url", 400
    await reasons.add_reason(get_topic(request.host), text, link)
    return redirect('/')


@bp.route('/vote/<reason_uuid>', methods=('POST',))
async def vote(reason_uuid):
    await reasons.vote_reason(get_topic(request.host), reason_uuid)
    return redirect('/')


def subdomain_used(hostheader: str) -> bool:
    """ True if any subdomain is used (apart from 'www.') """
    return bool(re.match(
        '^(?!www\\.).+\\.(pieceof\\.sh|localhost)(:[0-9]+)?$',
        hostheader
    ))


def get_topic(host: str) -> str:
    """ Strip 'pieceof.sh' from host header,
    and replace certain characters with spaces
    (and also e.g. localhost:5000 for local development)
    """
    # remove main domain from host header
    subdomain = re.sub('\\.(pieceof\\.sh|localhost)(:[0-9]+)*$', '',
                       host, flags=re.IGNORECASE)

    # decode idna encoding (for unicode in urls)
    if 'xn--' in subdomain:
        subdomain = bytes(subdomain, 'utf8').decode('idna')

    # '-', '_', and '.' become spaces
    topic = re.sub('[_\\-\\.]', ' ', subdomain)
    logger.debug(f"Host: {host} -> Topic: {topic}")
    return topic.lower()

pieceofsh/templates/base.j2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>

  <body>
    <nav class="navbar is-primary">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://pieceof.sh"><b>PIECE OF </b> 💩</a>
      </div>
    </nav>

    <br/>
    <br/>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

pieceofsh/templates/default.j2.html
{% extends 'base.j2.html' %}

{% block content %}
  {# shit header #}
  <center>
    <h1 class="title is-1 has-text-primary">Is there a specific</h1>
    <img class="image is-128x128" src='{{ url_for('static', filename='sh.png') }}'/>
    <h1 class="title is-1 has-text-primary">you are looking for?</h1>

    {# text field that goes to a specific-topic page #}
    <form action="/redirect" method="post" class="form">
      <div class="level">
        <input pattern=".+" required type="text" name="topic" class="input is-large is-primary"/>
        <button type="submit" class="button is-large is-primary">Go!</button>
      </div>
    </form>

    {# TODO: idea - random existing topic #}
    {# TODO: idea - list some popular topics #}

  </center>
{% endblock %}

pieceofsh/templates/reasoncard.j2.html
  {# script to show and hide reason card #}
  <script>
    function getCard() {
      return document.getElementById("reasoncard");
    }
    function showCard() {
      getCard().classList.add("is-active");
    }
    function hideCard() {
      getCard().classList.remove("is-active");
    }
  </script>

  {# modal reason card #}
  <div class="modal" id="reasoncard">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title"><b>+</b> Add a reason</p>
        {# TODO: fix icon here #}
        <button class="delete" onclick="hideCard()" aria-label="close"></button>
      </header>

      <form class="form" action="/new_reason" method="post">
        <section class="modal-card-body">
          <label class="label is-large" for="text">Why?</label>
          {# text #}
          <input required class="input is-medium" type="text" name="text" id="text" pattern=".{2,80}" title="Enter 2-80 characters" placeholder="Just because?"/>
          <br>
          <br>
          {# link #}
          <label class="label is-small" for="link">(Optional: add a link)</label>
          <input class="input is-small" type="url" name="link" id="link" placeholder="https://..."/>
        </section>

        <footer class="modal-card-foot">
          <button class="button is-primary" type="submit">Submit</button>
          <button class="button" onclick="hideCard()">Cancel</button>
        </footer>
      </form>
    </div>
  </div> {# // reason card #}

pieceofsh/templates/topic.j2.html
{% extends 'base.j2.html' %}


{% block content %}
  {% include 'reasoncard.j2.html' %}

  {# shit header #}
  <center>
    <section class="section">
        <h1 class="title is-1 has-text-primary">Yes, <br/> {{ topic }} <br/> is a piece of</h1>
        <img class="image is-128x128" src='{{ url_for('static', filename='sh.png') }}'/>
    </section>

    {# list of shitty reasons #}
    <section class="section">
      <table class="table is-narrow">
        <tr>
          <td colspan="3">
            <h1 class="title is-5 has-text-warning">
              Because...
            </h1>
          </td>
        </tr>

        {% if not reasons %}
          <tr>
            <td/>
            <td>Nobody has added a reason yet.</td>
          </tr>
        {% endif %}

        {% for reason in reasons %}
          <tr>
            <td>
              <form action="{{ url_for('views.vote', reason_uuid=reason.uuid) }}" method="post">
                <input class="button is-small is-primary" type="submit" value="▲"/>
              </form>
            </td>

            <td>{{ reason.votes }}</td>

            <td>
              {% if reason.link %}
                <a href="{{ reason.link }}"> {{ reason.text }} </a>
              {% else %}
                {{ reason.text }}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </section>

    {# TODO: hook button up to modal card #}
    <button class="button is-large is-fullwidth is-primary" onclick="showCard()">+ Add a reason</button>
  </center>

{% endblock %}